### ISSUE TITLE
excel delimiter fastcsv

### ISSUE THREAD

**Issue by shakilahmad23** [rebexnet/RebexTinySftpServer#10]

**Comment by lukas-m** [comment]
Can you please describe, what do you mean by issue "excel delimiter fastcsv"?

**Comment by shakilahmad23** [comment]
can you please delete the issue, by mistake created

> Can you please describe, what do you mean by issue "excel delimiter fastcsv"?

**Comment by lukas-m** [comment]
Closing unintentional issue.
