### ISSUE TITLE
[FEATURE] Ability to Clear Log 

### ISSUE THREAD

**Issue by thecliguy** [rebexnet/RebexTinySftpServer#2]
Thanks for producing this fantastic tool.

Would you consider adding the ability to clear the textbox that contains the log?

Rather than cluttering the UI with a dedicated button, I think a nice way to do this would be to right click the textbox and show a context menu with a "Clear" option.

**Comment by lukas-m** [comment]
Yeah, that makes sense. 
We will add it in a future version.

**Comment by lukas-m** [comment]
Added in v1.0.16.

**Comment by lukas-m** [comment]
Added in v1.0.16.
